package enums;
//(")([a-zA-Z ])([a-zA-Z\-'\(\) ]*)(") --> $1$2\L$3$4
public enum Stations {
	
	MAISSE("Maisse"),
	GROSLAY("Groslay"),
	LIMAY("Limay"),
	ISSOUPORCHEVILLE("Issou porcheville"),
	LANORVILLESAINTGERMAINLESARPAJON("La norville saint-germain les arpajon"),
	ORMOYVILLERS("Ormoy villers"),
	PARISAUSTERLITZGAREDAUSTERLITZ("Paris austerlitz (gare d'austerlitz)"),
	LEPERRAY("Le perray"),
	NOISYLEGRANDMONTDEST("Noisy le grand mont d'est"),
	HERICY("Hericy"),
	SAINTMARTINDETAMPES("Saint-martin d etampes"),
	MAULE("Maule"),
	PIERRELAYE("Pierrelaye"),
	AVENUEDUPRESIDENTKENNEDYMAISONDERADIOFRANCE("Avenue du president kennedy - maison de radio france"),
	PARISMONTPARNASSEGAREMONTPARNASSE("Paris montparnasse (gare montparnasse)"),
	ROSNYSOUSBOIS("Rosny sous bois"),
	PONTDELALMA("Pont de l'alma"),
	LOZERE("Lozere"),
	ERMONTHALTE("Ermont halte"),
	LONGUEVILLE("Longueville"),
	PROVINS("Provins"),
	CERGYLEHAUT("Cergy le haut"),
	ROISSYENBRIE("Roissy en brie"),
	COURCELLESURYVETTE("Courcelle sur yvette"),
	POISSY("Poissy"),
	FONTENAYAUXROSES("Fontenay aux roses"),
	PALAISEAUVILLEBON("Palaiseau villebon"),
	EPINAYSURORGE("Epinay sur orge"),
	CHAMPDECOURSESDENGHIEN("Champ de courses d'enghien"),
	CHAMARANDE("Chamarande"),
	EPINAYVILLETANEUSE("Epinay villetaneuse"),
	CLAMART("Clamart"),
	ESBLY("Esbly"),
	SARTROUVILLE("Sartrouville"),
	SAINTGERMAINENLAYEBELAIRFOURQUEUX("Saint-germain en laye bel air fourqueux"),
	PEREIRELEVALLOIS("Pereire levallois"),
	VILLENEUVETRIAGE("Villeneuve triage"),
	PORTEDECLICHY("Porte de clichy"),
	RUEILMALMAISON("Rueil malmaison"),
	VAUBOYEN("Vauboyen"),
	CRETEILPOMPADOUR("Creteil pompadour"),
	SAINTOUEN("Saint-ouen"),
	SANNOIS("Sannois"),
	ROSAPARKS("Rosa parks"),
	PORTROYAL("Port royal"),
	CESSON("Cesson"),
	ISSYVALDESEINE("Issy val de seine"),
	LAPLAINESTADEDEFRANCESAINTDENISAUBERVILLIERS("La plaine stade de france - saint-denis aubervilliers"),
	LABORNEBLANCHE("La borne blanche"),
	CHANTELOUPLESVIGNES("Chanteloup les vignes"),
	ABLON("Ablon"),
	ARGENTEUIL("Argenteuil"),
	MONTARGIS("Montargis"),
	MERIEL("Meriel"),
	CHAMPIGNY("Champigny"),
	CHARTRETTES("Chartrettes"),
	ANDRESY("Andresy"),
	SEVRESRIVEGAUCHE("Sevres rive gauche"),
	ORGERUSBEHOUST("Orgerus behoust"),
	TOURNAN("Tournan"),
	SAINTOUENLAUMONEQUARTIERDELEGLISE("Saint-ouen l'aumone quartier de l'eglise"),
	ROSNYBOISPERRIER("Rosny bois perrier"),
	PORCHEFONTAINE("Porchefontaine"),
	SAINTCHERON("Saint-cheron"),
	DAMMARTINJUILLYSAINTMARD("Dammartin juilly saint-mard"),
	ARPAJON("Arpajon"),
	THIEUXNANTOUILLET("Thieux nantouillet"),
	ROSNYSURSEINE("Rosny sur seine"),
	BESSANCOURT("Bessancourt"),
	CHANTILLYGOUVIEUX("Chantilly gouvieux"),
	LISLEADAMPARMAIN("L'isle adam parmain"),
	EGLY("Egly"),
	FERRIERESFONTENAY("Ferrieres fontenay"),
	AUVERSSUROISE("Auvers sur oise"),
	MORTCERF("Mortcerf"),
	MAISONSLAFFITTE("Maisons laffitte"),
	LESYVRISNOISYLEGRAND("Les yvris - noisy le grand"),
	NANTERREPREFECTURE("Nanterre prefecture"),
	NANTERREVILLE("Nanterre ville"),
	MONTGEROULTCOURCELLES("Montgeroult courcelles"),
	MAREILSURMAULDRE("Mareil sur mauldre"),
	MAREUILSUROURCQ("Mareuil sur ourcq"),
	NANTEUILSAACY("Nanteuil saacy"),
	MERYSUROISE("Mery sur oise"),
	NOINTELMOURS("Nointel mours"),
	VILLEPARISISMITRYLENEUF("Villeparisis mitry le neuf"),
	CHOISYLEROI("Choisy le roi"),
	LESCLAIRIERESDEVERNEUIL("Les clairieres de verneuil"),
	GRANDBOURG("Grand bourg"),
	LESNOUES("Les noues"),
	LARDY("Lardy"),
	FONTENAYLEFLEURY("Fontenay le fleury"),
	COULOMMIERS("Coulommiers"),
	LIANCOURTSAINTPIERRE("Liancourt saint pierre"),
	LEMEE("Le mee"),
	SEVRESVILLEDAVRAY("Sevres ville d'avray"),
	SAINTLEULAFORET("Saint-leu la foret"),
	LAGARENNECOLOMBES("La garenne colombes"),
	SAINTFARGEAU("Saint-fargeau"),
	VALMONDOIS("Valmondois"),
	THOMERY("Thomery"),
	DREUX("Dreux"),
	SURESNESMONTVALERIEN("Suresnes mont valerien"),
	CHAMPDEMARSTOUREIFFEL("Champ de mars tour eiffel"),
	RUNGISLAFRATERNELLE("Rungis la fraternelle"),
	SAINTREMYLAVANNE("Saint-remy la vanne"),
	BOISSYLAILLERIE("Boissy l'aillerie"),
	SALLEDESFETES("Salle des fetes"),
	PLAISIRGRIGNON("Plaisir grignon"),
	PONTPETIT("Pont petit"),
	MONTIGNYBEAUCHAMP("Montigny beauchamp"),
	GAREDENANTERREUNIVERSITERERA("Gare de nanterre universite rer a"),
	NEUILLYPLAISANCE("Neuilly plaisance"),
	GRAVIGNYBALIZY("Gravigny balizy"),
	LAFERTEMILON("La ferte milon"),
	ORSAYVILLE("Orsay ville"),
	MONTEREAU("Montereau"),
	GENTILLY("Gentilly"),
	MEUDON("Meudon"),
	MEAUX("Meaux"),
	PARISSAINTLAZAREGARESAINTLAZARE("Paris saint-lazare (gare saint-lazare)"),
	VERNOUSURSEINE("Vernou sur seine"),
	LIVRYSURSEINE("Livry sur seine"),
	PERSANBEAUMONT("Persan beaumont"),
	VAUXSURSEINE("Vaux sur seine"),
	LOUVECIENNES("Louveciennes"),
	LESBACONNETS("Les baconnets"),
	BELLEVUE("Bellevue"),
	GISORS("Gisors"),
	EMERAINVILLEPONTAULTCOMBAULT("Emerainville - pontault combault"),
	EPINAYSURSEINE("Epinay sur seine"),
	PARCDESCEAUX("Parc de sceaux"),
	LAPLACE("Laplace"),
	EPINAYSURSEINET11("EPINAY SUR SEINE T11"),
	EPINAYVILLETANEUSET11("EPINAY VILLETANEUSE T11"),
	LAVERRIERE("La verriere"),
	GIFSURYVETTE("Gif sur yvette"),
	IVRYSURSEINE("Ivry sur seine"),
	LESGRESILLONS("Les gresillons"),
	AUBERGENVILLEELISABETHVILLE("Aubergenville elisabethville"),
	LEBOURGET("Le bourget"),
	BECONLESBRUYERES("Becon les bruyeres"),
	CHEZYSURMARNE("Chezy sur marne"),
	LAGNYTHORIGNY("Lagny thorigny"),
	MARLYLEROI("Marly le roi"),
	BREUILLETBRUYERESLECHATEL("Breuillet bruyeres le chatel"),
	PETITJOUYLESLOGES("Petit jouy les loges"),
	NOGENTSURMARNE("Nogent sur marne"),
	GRIGNYCENTRE("Grigny centre"),
	AVENUEFOCH("Avenue foch"),
	ROBINSON("Robinson"),
	PRESLESCOURCELLES("Presles courcelles"),
	TRIELSURSEINE("Triel sur seine"),
	FREPILLON("Frepillon"),
	LUZARCHES("Luzarches"),
	VERSAILLESRIVEGAUCHECHATEAUDEVERSAILLES("VERSAILLES RIVE GAUCHE - CHÂTEAU DE VERSAILLES"),
	ORRYLAVILLECOYELAFORET("Orry la ville coye la foret"),
	MONTGERONCROSNE("Montgeron crosne"),
	CHATEAUTHIERRY("Chateau thierry"),
	PRECYSUROISE("Precy sur oise"),
	MONTRYCONDE("Montry conde"),
	BOUGIVAL("Bougival"),
	LACOURNEUVEAUBERVILLIERS("La courneuve aubervilliers"),
	LESBOULLEREAUXCHAMPIGNY("Les boullereaux champigny"),
	SUCYBONNEUIL("Sucy bonneuil"),
	LESARDOINES("Les ardoines"),
	LOGNES("Lognes"),
	NANTEUILLEHAUDOIN("Nanteuil le haudoin"),
	MONTIGNYSURLOING("Montigny sur loing"),
	SAINTDENIS("Saint-denis"),
	ACHERESVILLE("Acheres ville"),
	LECOUDRAYMONTCEAUX("Le coudray montceaux"),
	MEUDONVALFLEURY("Meudon val fleury"),
	SEVRANBEAUDOTTES("Sevran beaudottes"),
	BOISSISELEROI("Boissise le roi"),
	SERMAISE("Sermaise"),
	MAGENTA("Magenta"),
	ECOUENEZANVILLE("Ecouen ezanville"),
	BOISLEROI("Bois le roi"),
	ANGERVILLE("Angerville"),
	PIERREFITTESTAINS("Pierrefitte stains"),
	CHAPONVAL("Chaponval"),
	LESTADE("Le stade"),
	CHARS("Chars"),
	PARISGAREDELYON("Paris - gare de lyon"),
	SAINTEGENEVIEVEDESBOIS("Sainte-genevieve des bois"),
	DENFERTROCHEREAU("Denfert rochereau"),
	COUILLYSAINTGERMAINQUINCY("Couilly saint-germain quincy"),
	PARISBERCYGAREDEBERCY("Paris bercy (gare de bercy)"),
	VALDEUROPE("Val d'europe"),
	VERTGALANT("Vert galant"),
	NATION("Nation"),
	MONTSOULTMAFFLIERS("Montsoult maffliers"),
	CHAMPAGNESUROISE("Champagne sur oise"),
	SAINTOUENLAUMONELIESSE("Saint-ouen l'aumone liesse"),
	PONTDERUNGISAEROPORTDORLY("PONT DE RUNGIS Aéroport d'Orly"),
	ORLYVILLE("Orly ville"),
	RISORANGIS("Ris orangis"),
	SOUPPESCHATEAULANDON("SOUPPES CHÂTEAU LANDON"),
	OSNY("Osny"),
	AULNAYSOUSBOIS("Aulnay sous bois"),
	FRANCONVILLELEPLESSISBOUCHARD("Franconville le plessis bouchard"),
	NEUILLYPORTEMAILLOTPALAISDESCONGRES("Neuilly porte maillot - palais des congres"),
	BURESSURYVETTE("Bures sur yvette"),
	CHATOUCROISSY("Chatou croissy"),
	ETRECHY("Etrechy"),
	FONTAINELEPORT("Fontaine le port"),
	COLOMBES("Colombes"),
	HOUDAN("Houdan"),
	NEUVILLEUNIVERSITE("Neuville universite"),
	AEROPORTCHARLESDEGAULLE2TGVROISSY("AEROPORT CHARLES DE GAULLE 2 TGV - Roissy"),
	BOUSSYSAINTANTOINE("Boussy saint-antoine"),
	LACROIXDEBERNY("La croix de berny"),
	GARGESSARCELLES("Garges sarcelles"),
	SAINTSIMEON("Saint-simeon"),
	BOURAY("Bouray"),
	LAFERTESOUSJOUARRE("La ferte sous jouarre"),
	LACELLESAINTCLOUD("La celle saint-cloud"),
	GAGNY("Gagny"),
	SANTEUILLEPERCHAY("Santeuil le perchay"),
	BORANSUROISE("Boran sur oise"),
	HOUILLESCARRIERESSURSEINE("Houilles carrieres sur seine"),
	MASSYVERRIERES("Massy verrieres"),
	GAREDELADEFENSERERA("Gare de la defense rer a"),
	MARNELAVALLEECHESSY("Marne la vallee chessy"),
	GUERARDLACELLESURMORIN("Guerard la celle sur morin"),
	VILLABE("Villabe"),
	BOUFFEMONTMOISSELLES("Bouffemont moisselles"),
	JAVEL("Javel"),
	LESMUREAUX("Les mureaux"),
	BEYNES("Beynes"),
	GRETZARMAINVILLIERS("Gretz armainvilliers"),
	MAISONSALFORTALFORTVILLE("Maisons alfort alfortville"),
	FONTAINEMICHALON("Fontaine michalon"),
	MORETVENEUXLESSABLONS("Moret veneux les sablons"),
	CHAUFFRY("Chauffry"),
	MENNECY("Mennecy"),
	IGNY("Igny"),
	FONTENAYSOUSBOIS("Fontenay sous bois"),
	ATHISMONS("Athis mons"),
	ACHERESGRANDCORMIER("Acheres grand cormier"),
	EPONEMEZIERES("Epone mezieres"),
	GAREDENANTERREPREFECTURE("Gare de nanterre prefecture"),
	JOUYSURMORINMONUMENT("Jouy sur morin monument"),
	EVRYVALDESEINE("Evry - val de seine"),
	LEBLANCMESNIL("Le blanc mesnil"),
	LESSAULES("Les saules"),
	MONTFORTLAMAURYMERE("Montfort l'amaury mere"),
	ENGHIENLESBAINS("Enghien les bains"),
	LETANGLAVILLE("L'etang la ville"),
	SAINTOUENLAUMONE("Saint-ouen l'aumone"),
	BIBLIOTHEQUEFRANCOISMITTERRAND("Bibliotheque francois mitterrand"),
	CHAILLYBOISSYLECHATEL("Chailly boissy le chatel"),
	GENNEVILLIERS("Gennevilliers"),
	LEPLESSISBELLEVILLE("Le plessis belleville"),
	MARCHEZAISBROUE("Marchezais broue"),
	RAMBOUILLET("Rambouillet"),
	BONNIERES("Bonnieres"),
	SAINTREMYLESCHEVREUSE("Saint-remy les chevreuse"),
	AVENUEHENRIMARTIN("Avenue henri martin"),
	PONTHIERRYPRINGY("Ponthierry pringy"),
	BOIGNEVILLE("Boigneville"),
	PARISESTGAREDELEST("Paris est (gare de l'est)"),
	BRETIGNY("Bretigny"),
	SARCELLESSAINTBRICE("Sarcelles saint-brice"),
	BAGNEAUXSURLOING("Bagneaux sur loing"),
	THUNLEPARADIS("Thun le paradis"),
	SEUGY("Seugy"),
	BRUYERESSUROISE("Bruyeres sur oise"),
	MONTREUIL("Montreuil"),
	SAINTCYR("Saint-cyr"),
	SAINTMICHELNOTREDAMERERB("Saint-michel notre dame rer b"),
	SAINTNOMLABRETECHEFORETDEMARLY("Saint-nom la breteche foret de marly"),
	VAIRESTORCY("Vaires torcy"),
	VERNOUILLETVERNEUIL("Vernouillet verneuil"),
	VERSAILLESRIVEDROITE("Versailles rive droite"),
	VIARMES("Viarmes"),
	VILLENEUVELEROI("Villeneuve-le-roi"),
	VULAINESSURSEINESAMOREAU("Vulaines sur seine samoreau"),
	CONFLANSSAINTEHONORINE("Conflans sainte-honorine"),
	CREIL("Creil"),
	DRANCY("Drancy"),
	BALLANCOURT("Ballancourt"),
	CHAMPAGNESURSEINE("Champagne sur seine"),
	CHATELETLESHALLES("Chatelet les halles"),
	COIGNIERES("Coignieres"),
	DOMONT("Domont"),
	DOURDAN("Dourdan"),
	ETAMPES("Etampes"),
	LADEFENSE("La defense"),
	LAFRETTEMONTIGNY("La frette montigny"),
	SAVIGNYLETEMPLENANDY("Savigny le temple nandy"),
	VILLENEUVESAINTGEORGES("Villeneuve saint-georges"),
	TRAPPES("Trappes"),
	VALDEFONTENAY("Val de fontenay"),
	VERNEUILLETANG("Verneuil l'etang"),
	PANTIN("Pantin"),
	PLAISIRLESCLAYES("Plaisir les clayes"),
	VIRYCHATILLON("Viry chatillon"),
	VILLEPINTE("Villepinte"),
	BIEVRES("Bievres"),
	BAGNEUX("Bagneux"),
	CORMEILLESENPARISIS("Cormeilles en parisis"),
	ANTONY("Antony"),
	YERRES("Yerres"),
	CROUYSUROURCQ("Crouy sur ourcq"),
	PIERREFITTESTAINST11("PIERREFITTE-STAINS T11"),
	VILLIERSMONTBARBIN("Villiers montbarbin"),
	SAINTCLOUD("Saint-cloud"),
	VILLIERSLEBELGONESSEARNOUVILLE("Villiers le bel gonesse arnouville"),
	SAINTMAURCRETEIL("Saint-maur creteil"),
	OZOIRLAFERRIERE("Ozoir la ferriere"),
	SAINTGRATIEN("Saint-gratien"),
	TRIECHATEAU("Trie chateau"),
	PONTCARDINET("Pont cardinet"),
	SAINTMAMMES("Saint-mammes"),
	TRILPORT("Trilport"),
	CONFLANSFINDOISE("Conflans fin d'oise"),
	MELUN("Melun"),
	SAINTGERMAINENLAYE("Saint-germain en laye"),
	BOISSYSAINTLEGER("Boissy saint-leger"),
	LEVESINETCENTRE("Le vesinet centre"),
	BUNOGIRONVILLE("Buno gironville"),
	SEVRANLIVRY("Sevran livry"),
	SAINTECOLOMBESEPTVEILLES("Sainte-colombe septveilles"),
	MITRYCLAYE("Mitry claye"),
	BUSSYSAINTGEORGES("Bussy saint-georges"),
	CHARLESDEGAULLEETOILE("Charles de gaulle etoile"),
	ROUTEDEMONNERVILLE("Route de monnerville"),
	NOGENTLEPERREUX("Nogent le perreux"),
	SAVIGNYSURORGE("Savigny sur orge"),
	PETITVAUX("Petit vaux"),
	CHAUMONTENVEXIN("Chaumont en vexin"),
	COURBEVOIE("Courbevoie"),
	NANGIS("Nangis"),
	GAREDUNORDRER("Gare du nord rer"),
	VIGNEUXSURSEINE("Vigneux sur seine"),
	CHEMINDANTONY("Chemin d'antony"),
	CHILLYMAZARIN("Chilly mazarin"),
	GOUSSAINVILLE("Goussainville"),
	GARANCIERESLAQUEUE("Garancieres la queue"),
	TORCY("Torcy"),
	BELLOYSAINTMARTIN("Belloy saint-martin"),
	VANVESMALAKOFF("Vanves malakoff"),
	US("Us"),
	STADEDEFRANCESAINTDENIS("Stade de france saint-denis"),
	ORANGISBOISDELEPINE("Orangis bois de l'epine"),
	NOISYCHAMPS("Noisy champs"),
	LUXEMBOURG("Luxembourg"),
	TACOIGNIERESRICHEBOURG("Tacoignieres richebourg"),
	CHAVILLERIVEGAUCHE("Chaville rive gauche"),
	ISSY("Issy"),
	ERAGNYNEUVILLE("Eragny neuville"),
	VAUCRESSON("Vaucresson"),
	VAUCELLES("Vaucelles"),
	ERMONTEAUBONNE("Ermont eaubonne"),
	COMBSLAVILLEQUINCY("Combs la ville quincy"),
	GARGENVILLE("Gargenville"),
	LEBRASDEFEREVRYGENOPOLE("LE BRAS DE FER - Evry Génopole"),
	JOUYSURMORINEUSTACHE("Jouy sur morin eustache"),
	LAVARENNECHENNEVIERES("La varenne chennevieres"),
	LECHENAYGAGNY("Le chenay gagny"),
	JOUYENJOSAS("Jouy en josas"),
	MALESHERBES("Malesherbes"),
	LEGUICHET("Le guichet"),
	MARLESENBRIE("Marles en brie"),
	LESVALLEES("Les vallees"),
	JUZIERS("Juziers"),
	CHELLESGOURNAY("Chelles gournay"),
	AEROPORTCHARLESDEGAULLE1ROISSY("AEROPORT CHARLES DE GAULLE  1 - Roissy"),
	EVRYCOURCOURONNESCENTRE("Evry courcouronnes - centre"),
	CHAVILLEVELIZY("Chaville velizy"),
	LOUVRES("Louvres"),
	NOGENTLARTAUDCHARLY("Nogent l'artaud charly"),
	CRECYLACHAPELLE("Crecy la chapelle"),
	COMPANS("Compans"),
	MORMANT("Mormant"),
	VIROFLAYRIVEGAUCHE("Viroflay rive gauche"),
	MASSYPALAISEAU("Massy palaiseau"),
	MANTESLAJOLIE("Mantes la jolie"),
	PARCDESEXPOSITIONS("Parc des expositions"),
	CORBEILESSONNES("Corbeil essonnes"),
	LAHACQUINIERE("La hacquiniere"),
	GARCHESMARNESLACOQUETTE("Garches marnes la coquette"),
	MONDESIR("Mondesir"),
	LESESSARTSLEROI("Les essarts le roi"),
	SAINTMICHELNOTREDAMERERC("Saint michel notre dame rer c"),
	AUBER("Auber"),
	CHANGISSAINTJEAN("Changis saint-jean"),
	CLICHYLEVALLOIS("Clichy levallois"),
	CREPYENVALOIS("Crepy en valois"),
	SAINTQUENTINENYVELINES("Saint-quentin en yvelines"),
	SURVILLIERSFOSSES("Survilliers fosses"),
	BOURGLAREINE("Bourg la reine"),
	ARCUEILCACHAN("Arcueil cachan"),
	ISLESARMENTIERESCONGIS("Isles armentieres congis"),
	CHAVILLERIVEDROITE("Chaville rive droite"),
	BOISCOLOMBES("Bois colombes"),
	TAVERNY("Taverny"),
	VERNON("Vernon"),
	VERSAILLESCHANTIERS("Versailles chantiers"),
	VILLIERSSURMARNEPLESSISTREVISE("Villiers sur marne plessis trevise"),
	MAROLLESENHUREPOIX("Marolles en hurepoix"),
	PALAISEAU("Palaiseau"),
	GROSNOYERSAINTPRIX("Gros noyer saint-prix"),
	NEMOURSSAINTPIERRE("Nemours saint-pierre"),
	VIROFLAYRIVEDROITE("Viroflay rive droite"),
	CHAMPBENOISTPOIGNY("Champbenoist poigny"),
	NOISYLEROI("Noisy le roi"),
	MAURECOURT("Maurecourt"),
	PONTOISE("Pontoise"),
	PUTEAUX("Puteaux"),
	ESSONNESROBINSON("Essonnes robinson"),
	LIEUSAINTMOISSY("Lieusaint moissy"),
	INVALIDES("Invalides"),
	SAINTLEUDESSERENT("Saint-leu d esserent"),
	LAGRANDEPAROISSE("La grande paroisse"),
	VINCENNES("Vincennes"),
	VILLEPREUXLESCLAYES("Villepreux les clayes"),
	VILLENNESSURSEINE("Villennes sur seine"),
	VALDARGENTEUIL("Val d'argenteuil"),
	VILLAINES("Villaines"),
	CERGYPREFECTURE("Cergy prefecture"),
	ASNIERESSURSEINE("Asnieres sur seine"),
	LEVESINETLEPECQ("Le vesinet le pecq"),
	LAFERTEALAIS("La ferte alais"),
	BRYSURMARNE("Bry sur marne"),
	SCEAUX("Sceaux"),
	VOSVES("Vosves"),
	BRUNOY("Brunoy"),
	LABARREORMESSON("La barre ormesson"),
	BONDY("Bondy"),
	JOUYSURMORINCHAMPGOULIN("Jouy sur morin champgoulin"),
	LEPLESSISCHENET("Le plessis chenet"),
	JOINVILLELEPONT("Joinville le pont"),
	DOURDANLAFORET("Dourdan la foret"),
	VITRYSURSEINE("Vitry sur seine"),
	BOUTIGNY("Boutigny"),
	FAREMOUTIERSPOMMEUSE("Faremoutiers pommeuse"),
	DEUILMONTMAGNY("Deuil montmagny"),
	PONTDUGARIGLIANOHOPITALEUROPEENGEORGESPOMPIDOU("PONT DU GARIGLIANO - Hôpital Européen Georges Pompidou"),
	MOULINGALANT("Moulin galant"),
	MEULANHARDRICOURT("Meulan hardricourt"),
	MANTESSTATION("Mantes station"),
	CREDITAGRICOLEDOMMERVILLE("Credit agricole (dommerville)"),
	SAINTMICHELSURORGE("Saint-michel sur orge"),
	LEBOURGETT11("LE BOURGET T11"),
	CITEUNIVERSITAIRE("Cite universitaire"),
	SAINTGERMAINENLAYEGRANDECEINTURE("Saint-germain en laye grande ceinture"),
	MONNERVILLECENTRE("Monnerville centre"),
	BOULAINVILLIERS("Boulainvilliers"),
	VILLIERSNEAUPHLEPONTCHARTRAIN("Villiers neauphle pontchartrain"),
	NOISIEL("Noisiel"),
	LERAINCYVILLEMONBLEMONTFERMEIL("Le raincy villemonble montfermeil"),
	LAFERTEGAUCHERCENTRE("La ferte gaucher centre"),
	HAUSSMANNSAINTLAZARE("Haussmann saint-lazare"),
	LEPARCDESAINTMAUR("Le parc de saint-maur"),
	LONGJUMEAU("Longjumeau"),
	BOURRONMARLOTTEGREZ("Bourron marlotte grez"),
	FONTAINEBLEAUAVON("Fontainebleau avon"),
	LIZYSUROURCQ("Lizy sur ourcq"),
	HERBLAY("Herblay"),
	CERGYSAINTCHRISTOPHE("Cergy saint-christophe"),
	NOISYLESEC("Noisy le sec"),
	BREUILLETVILLAGE("Breuillet village"),
	MUSEEDORSAY("Musee d'orsay"),
	LAVILLETERTRE("La villetertre"),
	NEZELAULNAY("Nezel aulnay"),
	MAREILMARLY("Mareil marly"),
	DORDIVES("Dordives"),
	EPLUCHES("Epluches"),
	MOUROUX("Mouroux"),
	PARISNORDGAREDUNORD("Paris nord (gare du nord)"),
	JUVISY("Juvisy"),
	LEVALDOR("Le val d'or"),
	LEVERTDEMAISONS("Le vert de maisons");
		
	private String name;

	private Stations(String name){
		this.name = name;
	}

	public String getName() {
		return name;
	}
}
